### ISSUE TITLE
fix: Need to update descendant mapping separated from other assets

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#158]
## Motivation

This is so descendant mappings can be updated and paused separately from other assets. This allows frontend to always grab latest and also gives us the flexibility to prevent updates if needed.

## Definition of Done
Add more control to when descendant mapping is updated to prevent breaking the frontend filters. We should be able to update, and pause updating of these files without blocking development on main.

## Tasks

- [x] add a way to pin a branch that always has the descendant mappings the frontend should use.
- [x] automate updating that pin 
- [ ] add documentation how to pause and resume updating of descendant mappings. This is the GHA that updates them https://github.com/chanzuckerberg/cellxgene-ontology-guide/blob/main/.github/workflows/generate_decendant_mapping.yml
